SELECT TOP (1000) [ID]
      ,[CustomerID]
      ,[Order_Status]
      ,[Order_Date]
      ,[Total_Price]
      ,[Delivery_Date]
      ,[delivery_var]
      ,[delivery_Status]
  FROM [Magic_mart].[dbo].[Orders]
